/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const _CaffeineStorageCreateCertificateResult = IDL.Record({
  'method' : IDL.Text,
  'blob_hash' : IDL.Text,
});
export const _CaffeineStorageRefillInformation = IDL.Record({
  'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
});
export const _CaffeineStorageRefillResult = IDL.Record({
  'success' : IDL.Opt(IDL.Bool),
  'topped_up_amount' : IDL.Opt(IDL.Nat),
});
export const UserRole = IDL.Variant({
  'admin' : IDL.Null,
  'user' : IDL.Null,
  'guest' : IDL.Null,
});
export const SharedAlbum = IDL.Record({
  'id' : IDL.Text,
  'name' : IDL.Text,
  'photoIds' : IDL.Vec(IDL.Text),
});
export const ExternalBlob = IDL.Vec(IDL.Nat8);
export const Time = IDL.Int;
export const Photo = IDL.Record({
  'id' : IDL.Text,
  'blob' : ExternalBlob,
  'name' : IDL.Text,
  'createdAt' : Time,
});
export const ListAlbumPhotosResponse = IDL.Record({
  'photos' : IDL.Vec(Photo),
  'nextCursor' : IDL.Opt(IDL.Nat),
});
export const ListPhotosResponse = IDL.Record({
  'photos' : IDL.Vec(Photo),
  'nextCursor' : IDL.Opt(IDL.Nat),
});
export const UserProfile = IDL.Record({ 'name' : IDL.Text });

export const idlService = IDL.Service({
  '_caffeineStorageBlobIsLive' : IDL.Func(
      [IDL.Vec(IDL.Nat8)],
      [IDL.Bool],
      ['query'],
    ),
  '_caffeineStorageBlobsToDelete' : IDL.Func(
      [],
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      ['query'],
    ),
  '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
      [IDL.Vec(IDL.Vec(IDL.Nat8))],
      [],
      [],
    ),
  '_caffeineStorageCreateCertificate' : IDL.Func(
      [IDL.Text],
      [_CaffeineStorageCreateCertificateResult],
      [],
    ),
  '_caffeineStorageRefillCashier' : IDL.Func(
      [IDL.Opt(_CaffeineStorageRefillInformation)],
      [_CaffeineStorageRefillResult],
      [],
    ),
  '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
  '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
  'addPhotosToAlbum' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
  'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
  'createAlbum' : IDL.Func([IDL.Text], [], []),
  'deleteAlbum' : IDL.Func([IDL.Text], [], []),
  'deletePhoto' : IDL.Func([IDL.Text], [], []),
  'getAlbum' : IDL.Func([IDL.Text], [SharedAlbum], ['query']),
  'getAlbumPhoto' : IDL.Func([IDL.Text, IDL.Text], [Photo], ['query']),
  'getAlbumPhotosPaginated' : IDL.Func(
      [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [ListAlbumPhotosResponse],
      ['query'],
    ),
  'getAllPhotosPaginated' : IDL.Func(
      [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [ListPhotosResponse],
      ['query'],
    ),
  'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
  'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
  'getPhoto' : IDL.Func([IDL.Text], [Photo], ['query']),
  'getUserPhoto' : IDL.Func([IDL.Principal, IDL.Text], [Photo], ['query']),
  'getUserPhotosPaginated' : IDL.Func(
      [IDL.Principal, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
      [ListPhotosResponse],
      ['query'],
    ),
  'getUserProfile' : IDL.Func(
      [IDL.Principal],
      [IDL.Opt(UserProfile)],
      ['query'],
    ),
  'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
  'listAlbums' : IDL.Func([], [IDL.Vec(SharedAlbum)], ['query']),
  'removePhotoFromAlbum' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'renameAlbum' : IDL.Func([IDL.Text, IDL.Text], [], []),
  'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
  'uploadMultiplePhotos' : IDL.Func([IDL.Vec(Photo)], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const _CaffeineStorageCreateCertificateResult = IDL.Record({
    'method' : IDL.Text,
    'blob_hash' : IDL.Text,
  });
  const _CaffeineStorageRefillInformation = IDL.Record({
    'proposed_top_up_amount' : IDL.Opt(IDL.Nat),
  });
  const _CaffeineStorageRefillResult = IDL.Record({
    'success' : IDL.Opt(IDL.Bool),
    'topped_up_amount' : IDL.Opt(IDL.Nat),
  });
  const UserRole = IDL.Variant({
    'admin' : IDL.Null,
    'user' : IDL.Null,
    'guest' : IDL.Null,
  });
  const SharedAlbum = IDL.Record({
    'id' : IDL.Text,
    'name' : IDL.Text,
    'photoIds' : IDL.Vec(IDL.Text),
  });
  const ExternalBlob = IDL.Vec(IDL.Nat8);
  const Time = IDL.Int;
  const Photo = IDL.Record({
    'id' : IDL.Text,
    'blob' : ExternalBlob,
    'name' : IDL.Text,
    'createdAt' : Time,
  });
  const ListAlbumPhotosResponse = IDL.Record({
    'photos' : IDL.Vec(Photo),
    'nextCursor' : IDL.Opt(IDL.Nat),
  });
  const ListPhotosResponse = IDL.Record({
    'photos' : IDL.Vec(Photo),
    'nextCursor' : IDL.Opt(IDL.Nat),
  });
  const UserProfile = IDL.Record({ 'name' : IDL.Text });
  
  return IDL.Service({
    '_caffeineStorageBlobIsLive' : IDL.Func(
        [IDL.Vec(IDL.Nat8)],
        [IDL.Bool],
        ['query'],
      ),
    '_caffeineStorageBlobsToDelete' : IDL.Func(
        [],
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        ['query'],
      ),
    '_caffeineStorageConfirmBlobDeletion' : IDL.Func(
        [IDL.Vec(IDL.Vec(IDL.Nat8))],
        [],
        [],
      ),
    '_caffeineStorageCreateCertificate' : IDL.Func(
        [IDL.Text],
        [_CaffeineStorageCreateCertificateResult],
        [],
      ),
    '_caffeineStorageRefillCashier' : IDL.Func(
        [IDL.Opt(_CaffeineStorageRefillInformation)],
        [_CaffeineStorageRefillResult],
        [],
      ),
    '_caffeineStorageUpdateGatewayPrincipals' : IDL.Func([], [], []),
    '_initializeAccessControlWithSecret' : IDL.Func([IDL.Text], [], []),
    'addPhotosToAlbum' : IDL.Func([IDL.Text, IDL.Vec(IDL.Text)], [], []),
    'assignCallerUserRole' : IDL.Func([IDL.Principal, UserRole], [], []),
    'createAlbum' : IDL.Func([IDL.Text], [], []),
    'deleteAlbum' : IDL.Func([IDL.Text], [], []),
    'deletePhoto' : IDL.Func([IDL.Text], [], []),
    'getAlbum' : IDL.Func([IDL.Text], [SharedAlbum], ['query']),
    'getAlbumPhoto' : IDL.Func([IDL.Text, IDL.Text], [Photo], ['query']),
    'getAlbumPhotosPaginated' : IDL.Func(
        [IDL.Text, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [ListAlbumPhotosResponse],
        ['query'],
      ),
    'getAllPhotosPaginated' : IDL.Func(
        [IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [ListPhotosResponse],
        ['query'],
      ),
    'getCallerUserProfile' : IDL.Func([], [IDL.Opt(UserProfile)], ['query']),
    'getCallerUserRole' : IDL.Func([], [UserRole], ['query']),
    'getPhoto' : IDL.Func([IDL.Text], [Photo], ['query']),
    'getUserPhoto' : IDL.Func([IDL.Principal, IDL.Text], [Photo], ['query']),
    'getUserPhotosPaginated' : IDL.Func(
        [IDL.Principal, IDL.Opt(IDL.Nat), IDL.Opt(IDL.Nat)],
        [ListPhotosResponse],
        ['query'],
      ),
    'getUserProfile' : IDL.Func(
        [IDL.Principal],
        [IDL.Opt(UserProfile)],
        ['query'],
      ),
    'isCallerAdmin' : IDL.Func([], [IDL.Bool], ['query']),
    'listAlbums' : IDL.Func([], [IDL.Vec(SharedAlbum)], ['query']),
    'removePhotoFromAlbum' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'renameAlbum' : IDL.Func([IDL.Text, IDL.Text], [], []),
    'saveCallerUserProfile' : IDL.Func([UserProfile], [], []),
    'uploadMultiplePhotos' : IDL.Func([IDL.Vec(Photo)], [], []),
  });
};

export const init = ({ IDL }) => { return []; };